package org.jboss.fuse.workshop.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000243-redhat-1
 * 2019-03-26T14:24:11.521+07:00
 * Generated source version: 3.1.11.fuse-000243-redhat-1
 * 
 */
@WebService(targetNamespace = "http://soap.workshop.fuse.jboss.org/", name = "EmployeeWSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeWSPortType {

    @WebMethod
    @RequestWrapper(localName = "getEmployeeAll", targetNamespace = "http://soap.workshop.fuse.jboss.org/", className = "org.jboss.fuse.workshop.soap.GetEmployeeAll")
    @ResponseWrapper(localName = "getEmployeeAllResponse", targetNamespace = "http://soap.workshop.fuse.jboss.org/", className = "org.jboss.fuse.workshop.soap.GetEmployeeAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.jboss.fuse.workshop.soap.EmployeeList getEmployeeAll();

    @WebMethod
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://soap.workshop.fuse.jboss.org/", className = "org.jboss.fuse.workshop.soap.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://soap.workshop.fuse.jboss.org/", className = "org.jboss.fuse.workshop.soap.AddEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.jboss.fuse.workshop.soap.Employee addEmployee(
        @WebParam(name = "arg0", targetNamespace = "http://soap.workshop.fuse.jboss.org/")
        org.jboss.fuse.workshop.soap.Employee arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://soap.workshop.fuse.jboss.org/", className = "org.jboss.fuse.workshop.soap.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://soap.workshop.fuse.jboss.org/", className = "org.jboss.fuse.workshop.soap.GetEmployeeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.jboss.fuse.workshop.soap.Employee getEmployee(
        @WebParam(name = "arg0", targetNamespace = "http://soap.workshop.fuse.jboss.org/")
        java.lang.Integer arg0
    );
}
